version: 2
general:
  branches:
    only:
      - master
      - develop
      - /feature/.*/
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/apollo-client-maven-plugin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: |
          mvn dependency:resolve-plugins
          mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn clean test

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/apollo-client-maven-plugin
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: |
          mvn dependency:resolve-plugins
          mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Deploy the artifacts
          command: |
            mvn -s ./.circleci/.circleci.settings.xml -DskipTests deploy -P bintray
  sync:
    docker:
      - image: byrnedo/alpine-curl:0.1.8
    steps:
      - run:
          name: Sync version Artifacts to Maven Central
          command: |
            curl -d '{"username": "${SONATYPE_USER_TOKEN}", "password": "${SONATYPE_PASSWORD}"}' -H "Content-Type: application/json" -X POST https://bintray.com/maven_central_sync/sparow199/maven/apollo-client-maven-plugin/3.2.0-SNAPSHOT

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            # only act on version tags
            tags:
              only: /^v\d+\.\d+\.\d+$/
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
      - sync:
          requires:
            - deploy
          filters:
            # only act on version tags
            tags:
              only: /^v\d+\.\d+\.\d+$/
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
